package org.devcloud.waypoints.config

object LanguagePath {
    const val PREFIX = "prefix"
    const val POINT_NAME = "pointName"
    const val POINT_CREATED = "pointCreated"
    const val POINT_RECREATED = "pointReCreated"
    const val POINT_DELETED = "pointDeleted"
    const val POINT_NOT_FOUND = "pointNotFound"
    const val POINT_LIST_DELETE = "pointListDelete"
    const val POINT_LIST_EMPTY = "pointListEmpty"
    const val HOVER_MESSAGE = "hoverMessage"
    const val PERMISSION_DENY = "permissionDeny"
    const val CHOOSE_TYPE = "chooseType"
    const val CHOOSE_WAYPOINT = "chooseWayPoint"
    const val UNKNOWN_CURSOR_TYPE = "unknownCursorType"
    const val HIDE_TYPE_ERROR = "hideTypeError"
    const val HIDE = "hide"
    const val UN_HIDE = "unHide"
    const val ENTER_NAME = "enterName"
    const val DIFFERENT_TYPE = "differentType"
    const val MAX_POINTS = "maxPoints"
    const val WAYPOINT_NAME_HINT = "wayPointNameHint"
    const val HELP = "help"
    const val ADMIN_HELP = "adminHelp"
}